# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.AddField(
            model_name='taskdescription',
            name='description',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='description', to='tasks.Task'),
            preserve_default=False,
        ),
    ]
