# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-16 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20180616_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdescription',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='tasks.TaskDescription'),
            preserve_default=False,
        ),
    ]
